chapter 1 to 7
AndreiMischie/OnlineShopFE pull request #1
Opened 2023-07-31 06:50 UTC by AndreiMischie

2023-07-31 09:01 UTC, AndreiSold requested changes

2023-07-31 09:01 UTC, AndreiSold commented on README.md
> +# OnlineShop
FYI this read me file appears when opening a repo's homepage. I would suggest to either customize it to a minimum or completely remove it

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app-routing.module.ts
> +export enum Paths {
I like how you extracted to paths into a single data unit but it's usually recommended to use a JSON structure as you can also group sub-paths together. Also, some other points woul be those:

- you should also hold a path for the homepage of your app and use it in routes, even if you redirect to the products list page
- when you have a path with the ID you should store the full path as you did on line 16. So you would have a route called `PRODUCT_DETAILS = 'product-details/:id` which you currently have but don't use here, and when you want to redirect to it with an actual id you can do `PRODUCT_DETAILS.replace(":id", actualId)`, or use the params object
- as a good practice you should have a 404 path at the end of the router, which is accessed by `*` and catches all the paths that are tried to be accesed but do not exist. Usually a 404 page is shown in that case
- don't forget the first point of holding the paths values in a JSON object, something like: `export const paths = { shoppingCart: 'shopping-cart', ... }`

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app-routing.module.ts
> +  { path: '', redirectTo: Paths.PRODUCT_LIST, pathMatch: 'full' },
Great usage of redirect to here

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app-routing.module.ts
> +  { path: 'product-details/:id', component: ProductDetailsComponent },
This should also be a value from the paths object

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app.component.html
> +<button (click)="getProducts()">get</button>
The products should only be retrieved in the products list page, the root app component should have no knowledge of any back-end data or requests. It should be dumb, only referencing to components and the router outlet (exception only for authentication)

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app.component.ts
> +@Component({
Try to make it a habit to use empty lines for letting code components breathe, for example here you could put one above the component definition

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app.component.ts
> +  getProducts() {
Same here, first you should group together similar attributes (products and title) and then add empty lines between the code blocks

2023-07-31 09:01 UTC, AndreiSold commented on src/app/app.module.ts
> +
Here there is no usage for this empty line, you can hold all imports in a single block

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/containers/product-details/product-details.component.ts
> +  productDetails: Observable<Products> | undefined;
I see multiple issue here:

- you have one product so the type should be `Product` not `Products`
- you generate an Observable and pass it to the view component which should be dumb, instead of getting the product data here and only passing that (through a Subscription (example: https://www.delftstack.com/howto/angular/angular-subscribe/)
- additionaly to the above subscription we need to close the subscription channel after usage but contact me and I will show you how
- you currently only use `async pipes` to get the data from an observable, this subscription solution is an alternative approach in which you can also store the data in an attribute
- if you have something that can be `undefined`, putting an `?` after it's name would be the same as adding ` | undefined`

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/containers/product-details/product-details.component.ts
> +  nullToUndefined(text: string | null): string | undefined {
This does not really make sense at all as null and undefined can be considered the same when writing JS logic, as `falsies`. Remove the function and try to change the logic to work without it

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/containers/product-details/product-details.component.ts
> +  getProduct(id: string | null): void {
The function should always know exactly what values it should receive, so here you shouldn't have `| null`, instead you must check if `id` exists in the function that calls this one

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/containers/product-details/product-details.component.ts
> +      this.productDetails = this.http.get<Products>(
Here is the place where you would subscribe to the observable and then assign the actual data object to an attribute, not the observable object

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/containers/products-list/products-list.component.ts
> +  productsList: Observable<Products[]> | undefined;
Same observations and changes required as for the details component

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/presentational/product-details-view/product-details-view.component.html
> +    <!-- <h1>Product:{{ productDetails.name }}</h1> -->
Make a habbit to never push commented code, remove it

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/presentational/products-list-view/products-list-view.component.html
> +        <a [routerLink]="['../product-details', product.id]">
Use the `paths` object here when building the route

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/presentational/products-list-view/products-list-view.component.html
> +<router-outlet></router-outlet>
Another router outlet here? Do you have a secondary routing config for subroutes?

2023-07-31 09:01 UTC, AndreiSold commented on src/app/components/presentational/products-list-view/products-list-view.component.ts
> +  @Input() productsList: Observable<Products[]> | undefined;
Same here as for the details components

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shared/components/presentational/icon-button/icon-button.component.ts
> +  @Input() icon: string | undefined;
Use the `?` optional marker

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shopping-cart/components/presentational/shopping-cart-view/shopping-cart-view.component.scss
> +.table{
I see that this styling properties are duplicated with the ones from the `products list` I think. To reuse them you can put them in the root styling file, as anyway you want to globally change the styling of the primitive html elements

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shopping-cart/components/presentational/shopping-cart-view/shopping-cart-view.component.ts
> +  @Input() products: Products[] | undefined;
Same here

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shopping-cart/services/shopping-cart.service.ts
> +  addProductToCart(id: string, product: Products): void {
Let the methods breeeeeeaaaaaattthheeee

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shopping-cart/services/shopping-cart.service.ts
> +  addProductToCart(id: string, product: Products): void {
Again a missed type here: `product: Products`, you only have **ONE**

2023-07-31 09:01 UTC, AndreiSold commented on src/app/modules/shopping-cart/services/shopping-cart.service.ts
> +    return JSON.parse(product);
Why not always return a list/array but sometimes it's empty? It's cleaner than using null. Also, make a habit to use undefined because it's the same and it's more commonly used in JS/TS

2023-07-31 12:48 UTC, AndreiMischie commented on src/app/app.component.html
> +<button (click)="getProducts()">get</button>
this was only for testing and i forgot to delete it

2023-07-31 12:52 UTC, AndreiMischie commented on src/app/app-routing.module.ts
> +  { path: '', redirectTo: Paths.PRODUCT_LIST, pathMatch: 'full' },
thanks

2023-07-31 12:52 UTC, AndreiMischie commented on README.md
> +# OnlineShop
done

2023-07-31 12:53 UTC, AndreiMischie commented on src/app/app-routing.module.ts
> +  { path: 'product-details/:id', component: ProductDetailsComponent },
done

2023-07-31 12:54 UTC, AndreiMischie commented on src/app/modules/shared/components/presentational/icon-button/icon-button.component.ts
> +  @Input() icon: string | undefined;
done

2023-07-31 13:03 UTC, AndreiMischie commented on src/app/modules/shopping-cart/services/shopping-cart.service.ts
> +    return JSON.parse(product);
done

2023-08-03 06:39 UTC, AndreiMischie commented on src/app/app-routing.module.ts
> +export enum Paths {
done

2023-08-03 06:40 UTC, AndreiMischie commented on src/app/modules/shopping-cart/components/presentational/shopping-cart-view/shopping-cart-view.component.scss
> +.table{
done

2023-08-03 06:42 UTC, AndreiMischie commented on src/app/modules/shopping-cart/services/shopping-cart.service.ts
> +  addProductToCart(id: string, product: Products): void {
done

2023-08-03 06:42 UTC, AndreiMischie commented on src/app/modules/shopping-cart/components/presentational/shopping-cart-view/shopping-cart-view.component.ts
> +  @Input() products: Products[] | undefined;
done

2023-08-03 10:22 UTC, merged